# Generated by Django 4.0.6 on 2022-07-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
